on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Test SSH Connection
      run: |
        nc -zv ${{ secrets.SSH_HOST }} 22

    - name: Deploy using SSH
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
        cd ~/Documents/backend
        git pull origin main
        npm install --only=prod
        EOF
