name: Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using SSH
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no
        ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "bash -s" <<EOF
        cd ~/Documents/backend
        git pull origin main
        npm install --only=prod
        EOF
