name: remote ssh command
on: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
        timeout: 60s
        command_timeout: 15m
