name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 192.168.31.71
          username: sourab
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd ~/Documents/backend
            git pull origin main
            npm install
            npm run build
            pm2 delete all
            pm2 start npm --name "backend" -- start