name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Copy files to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ sourab@192.168.31.71:~/Documents/backend

    - name: SSH into VPS and restart server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no sourab@192.168.31.71 << 'EOF'
          cd /var/www/myapp
          npm install --production
          pm2 reload all || pm2 start dist/main.js --name "my-nest-app"
        EOF
